version: '3.1'
services:

  ewm-service:
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
#      - SPRING_DATASOURCE_URL=jdbc:h2:mem:ewm
#      - SPRING_DATASOURCE_USERNAME=test
#      - SPRING_DATASOURCE_PASSWORD=test

  ewm-db:
    image: postgres:14-alpine
#    depends_on:
#      - stats-server
    container_name: ewm
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root



  stats-server:
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
#        - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
#        - SPRING_DATASOURCE_URL=jdbc:h2:mem:stats
#        - SPRING_DATASOURCE_USERNAME=test
#        - SPRING_DATASOURCE_PASSWORD=test


  stats-db:
    image: postgres:14-alpine
    container_name: stats
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root